site_name: summary.dev
site_url: https://summary.dev/docs
repo_url: https://github.com/SummaryDev/documentation
edit_uri: blob/main/docs
site_description: Summary is a blockchain indexer for StarkNet and Ethereum and a suite of developer tools for Web3
copyright: !ENV [copyright, sha_short, namespace]

theme:
    name: mkdocs
    custom_dir: custom_theme/
    highlightjs: true
    hljs_languages:
      - graphql

nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Queries: queries.md
    - SQL: sql.md
    - Subscriptions: subscriptions.md
