name: Deploy to nginx in EKS

on:
  workflow_dispatch:
#  push:
#    branches: [ main, stage, prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Compute variables
      id: var
      run: |
        if [[ ${{ github.ref_name }} == main ]]; then echo "::set-output name=namespace::dev"; else echo "::set-output name=namespace::${{ github.ref_name }}"; fi
        echo "::set-output name=sha_short::${GITHUB_SHA::7}"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to EKS
      uses: tensor-hq/eksctl-helm-action@0.1.0
      env:
        namespace: ${{ steps.var.outputs.namespace }}
        sha_short: ${{ steps.var.outputs.sha_short }}
      with:
        eks_cluster: dev-eks-starknet-indexer
        command: ./deploy.sh
